version: '3.9'

services:
  prometheus:
      image: prom/prometheus:latest
      volumes:
          - ./prometheus:/etc/prometheus
      command:
          - '--config.file=/etc/prometheus/prometheus.yaml'
      ports:
          - 9090:9090
  grafana:
      image: grafana/grafana:latest
      volumes:
          - ./grafana:/etc/grafana
      ports:
          - 3000:3000
      depends_on:
          - prometheus